language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

branches:
    only:
        - master
        - /^\d+\.\d+$/

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini
    - composer selfupdate

install: composer update --prefer-dist --no-interaction

script: ./bin/phpunit --debug
