language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

branches:
    only:
        - master
        - /^\d+\.\d+$/

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini
    - composer selfupdate

install: composer update --prefer-dist --no-interaction

script: ./bin/travis_phpunit
after_script:
    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
